spring:
  datasource:
    username: root
    password: admin123456
    url: jdbc:mysql://localhost:3306/joe_rbac?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
server:
  port: 8081
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml

# jwt config
jwt:
  secret: mySecret
  header: Authorization
  tokenHeader: Bearer
  expiration: 3600 #ms